services:
  server:
    build: server/
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    environment:
      - TIMEWEB_TOKEN=
      - TIMEWEB_SERVER_ID=
    networks:
      - main
  
  client:
    build: nginx/
    environment:
      - NGINX_HOST=
      - NGINX_PORT=80
      - SERVER_HOST=server
      - SERVER_PORT=5000
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - main

networks:
  main:
    driver: bridge
